# This is a basic workflow to help you get started with Actions

name: README badges

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-badges:
    name: Update Badges
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Badges - Readme
      uses: pemtajo/badge-readme@2.1.0
      with:
        CREDLY_USER: akshaya-raghuthaman.8d4add69
